#general_settings:
  #master_key: sk-ligma
litellm_settings:
  drop_params: true
model_list: 
  - model_name: gpt-3.5-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: openai/gpt-3.5-turbo
      temperature: 0.1
  - model_name: gemini/gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      temperature: 0.1
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo
      temperature: 0.1
