---
endpoint: https://jira.int.messagesystems.com

custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list -t table --query "assignee = currentUser() and project in (CM, SRE, ESCSP, TR) and status != closed and status != done order by status, rank"

  - name: trboard
    help: display all issues on the tr board
    options:
      - name: status_query
        short: s
        help: which status(es) to query, all quotes must be single quotes
        default: 'not in (Closed, Done, Backlog)'
      - name: order_by
        short: o
        help: what criteria to order by
        default: 'status'
    script: |-
      {{jira}} list -t yaakov-table --query "status {{options.status_query}} AND project = Transmissions AND ((resolution not in (Withdrawn, Duplicate) OR resolution is EMPTY) or (project in (ESCSP, ESC) and team = Transmissions )) and status != Backlog ORDER BY {{ options.order_by }}"

  - name: sre_escs 
    help: shows sre escalations
    options:
      - name: status_query
        short: s
        help: which status(es) to query, all quotes must be single quotes
        default: 'in (Backlog)'
    script: |-
      {{jira}} list -t yaakov-table --query "(status {{ options.status_query }}) AND (project in (ESCSP) AND (labels = SRE OR team in (SRE)) OR project in (SRE) AND issuetype = Interrupt or (project in (RCA) and team in (sre)) and (fixVersion in unreleasedVersions() OR fixVersion is EMPTY)) ORDER BY status ASC"

  - name: inreview
    help: moves a ticket to 'in review'
    args:
       - name: issue
    script: |-
      jira transition --noedit "In Review" {{ args.issue }}

  - name: startprogress
    help: moves a ticket to 'in progress'
    args:
      - name: issue
    script: |-
      jira transition --noedit 'Ready for Dev' {{ args.issue }} 
      jira transition --noedit 'Start Progress' {{ args.issue }}

  - name: superclose
    help: moves a ticket from the backlog through to closed
    args:
      - name: issue
    script: |-
      jira startprogress {{ args.issue }}
      jira inreview {{ args.issue }}
      jira close {{ args.issue }}

  - name: superduperclose
    help: moves a ticket through the full momentum workflow
    args:
      - name: issue
    script: |-
      jira superclose {{ args.issue }}
      jira transition --noedit "Hotfix - In Staging" {{ args.issue }}
      jira transition --noedit "Verified in Staging" {{ args.issue }}
      jira transition --noedit "In Production" {{ args.issue }}
      jira transition --noedit "Verified in Prod" {{ args.issue }}
      jira close {{ args.issue }}
